version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: syc-hair
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d syc-hair']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/syc-hair?schema=public&encoding=UTF8
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && yarn start"


volumes:
  postgres_data:
