import '@radix-ui/themes/styles.css';
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme, Container } from '@radix-ui/themes'
import NavBar from './NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SYC Hair Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Theme appearance='light' accentColor='indigo'>
          <NavBar />
          <main className='p-8'>
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  )
}
